# Generated by Django 3.1 on 2020-08-31 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField(blank=True)),
                ('product_url', models.TextField(blank=True)),
                ('price', models.TextField(blank=True)),
                ('shop_name', models.TextField(blank=True)),
                ('image_url', models.TextField(blank=True)),
            ],
        ),
    ]
