# Generated by Django 3.1 on 2020-09-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tfData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.TextField(blank=True)),
                ('product_info', models.TextField(blank=True)),
            ],
        ),
    ]
